# Replace the <<database_name>> with proper database name that is to be migrated.

USE <<database_name>>;

CREATE TABLE CSM_PASSWORD_HISTORY (
	ID NUMBER (11) NOT NULL,
	LOGIN_NAME VARCHAR2 (1500),
	PASSWORD VARCHAR2 (300)
); 
	
/
 
ALTER TABLE CSM_USER ADD ( PASSWORD_EXPIRED NUMBER(1) NOT NULL DEFAULT '0');
ALTER TABLE CSM_USER ADD ( PASSWORD_UPDATE_DATE DATE);
ALTER TABLE CSM_USER ADD ( FIRST_TIME_LOGIN  NUMBER(1) NOT NULL);
