/*L
   Copyright SAIC, SAIC-Frederick

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/common-security-module/LICENSE.txt for details.
L*/


UPDATE CSM_APPLICATION SET csm_application.DECLARATIVE_FLAG='0';

ALTER TABLE CSM_PROTECTION_ELEMENT DROP COLUMN PROTECTION_ELEMENT_TYPE_ID;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD COLUMN PROTECTION_ELEMENT_TYPE character varying(100);
ALTER TABLE CSM_PG_PE ALTER COLUMN UPDATE_DATE TYPE date;
ALTER TABLE CSM_APPLICATION UPDATE COLUMN APPLICATION_NAME character varying(255) NOT NULL;
ALTER TABLE CSM_GROUP UPDATE COLUMN GROUP_NAME character varying(255) NOT NULL;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD CONSTRAINT UQ_PE_OBJECT_ID_ATTRIBUTE_APP_ID UNIQUE (PROTECTION_ELEMENT_NAME, ATTRIBUTE, APPLICATION_ID);

ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_URL character varying(100);
ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_USER_NAME character varying(100);
ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_PASSWORD character varying(100);
ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_DIALECT character varying(100);
ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_DRIVER character varying(100);

UPDATE CSM_PG_PE SET UPDATE_DATE=NULL;
