/*L
   Copyright SAIC, SAIC-Frederick

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/common-security-module/LICENSE.txt for details.
L*/


ALTER TABLE CSM_USER ALTER COLUMN PHONE_NUMBER TYPE character varying(100);

ALTER TABLE CSM_USER ADD COLUMN PASSWORD_EXPIRED character varying(1) DEFAULT 0;
ALTER TABLE CSM_USER ADD COLUMN FIRST_TIME_LOGIN character varying(1) DEFAULT 0;
ALTER TABLE CSM_USER ADD COLUMN ACTIVE_FLAG character varying(1) DEFAULT 1;
ALTER TABLE CSM_USER ADD COLUMN PASSWORD_EXPIRY_DATE date DEFAULT '2012-10-10';

CREATE SEQUENCE CSM_PASSWORD_HISTORY_SEQ;

CREATE TABLE CSM_PASSWORD_HISTORY (
	CSM_PASSWORD_HISTORY_ID int8 default nextval('CSM_PASSWORD_HISTORY_SEQ'),
	LOGIN_NAME character varying(500),
	PASSWORD character varying(300),
	PRIMARY KEY(CSM_PASSWORD_HISTORY_ID)
);

CREATE TABLE CSM_CONFIGURATION_PROPS (
  PROPERTY_KEY character varying(300) NOT NULL,
  PROPERTY_VALUE character varying(3000),
  PRIMARY KEY (PROPERTY_KEY)
);

INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('AES_ENCRYPTION_KEY','super secret');
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('ALLOWED_ATTEMPTS','3');
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('ALLOWED_LOGIN_TIME','600000');
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('MD5_HASH_KEY','true');
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_EXPIRY_DAYS','60');
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_LOCKOUT_TIME','1800000');
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_MATCH_NUM','24');
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_PATTERN_MATCH','^.*(?=.{8,})(?=..*[0-9])(?=.*[a-z])(?=.*[A-Z]).*$');
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_PATTERN_DESCRIPTION','At least one Upper case alphabet, at least one lower case alphabet, at least one number and minimum 8 characters length');

COMMIT;
