/*L
   Copyright SAIC, SAIC-Frederick
   

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/common-security-module/LICENSE.txt for details.
L*/


ALTER TABLE CSM_USER ALTER COLUMN LOGIN_NAME TYPE character varying(500) NOT NULL;
ALTER TABLE CSM_USER ADD COLUMN MIGRATED_FLAG smallint DEFAULT 0 NOT NULL;
ALTER TABLE CSM_USER ADD COLUMN PREMGRT_LOGIN_NAME character varying(100) ;

ALTER TABLE CSM_PG_PE ALTER COLUMN UPDATE_DATE SET DEFAULT CURRENT_DATE;

ALTER TABLE CSM_ROLE_PRIVILEGE DROP COLUMN UPDATE_DATE;
ALTER TABLE CSM_USER_PE DROP COLUMN UPDATE_DATE;

ALTER TABLE CSM_FILTER_CLAUSE RENAME GENERATED_SQL TO GENERATED_SQL_USER;
ALTER TABLE CSM_FILTER_CLAUSE ADD COLUMN GENERATED_SQL_GROUP character varying (4000) NOT NULL;
