/*L
   Copyright SAIC, SAIC-Frederick

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/common-security-module/LICENSE.txt for details.
L*/

CREATE SEQUENCE CSM_MAPPING_SEQ;

CREATE TABLE CSM_MAPPING (
  MAPPING_ID int8 NOT NULL default nextval('CSM_MAPPING_SEQ'),
  APPLICATION_ID int8 NOT NULL,
  OBJECT_NAME character varying(100) NOT NULL,
  ATTRIBUTE_NAME character varying(100) NOT NULL,
  OBJECT_PACKAGE_NAME character varying(100),
  TABLE_NAME character varying(100),
  TABLE_NAME_GROUP character varying(100),
  TABLE_NAME_USER character varying(100),
  VIEW_NAME_GROUP character varying(100),
  VIEW_NAME_USER character varying(100),
  ACTIVE_FLAG character varying(1) DEFAULT 0 NOT NULL,
  MAINTAINED_FLAG character varying(1) DEFAULT 0 NOT NULL,	
  UPDATE_DATE date DEFAULT CURRENT_DATE NOT NULL,
  PRIMARY KEY(MAPPING_ID)
);

ALTER TABLE CSM_MAPPING ADD CONSTRAINT FK_PE_APPLICATION 
FOREIGN KEY (APPLICATION_ID) REFERENCES CSM_APPLICATION (APPLICATION_ID) ON DELETE CASCADE
;
ALTER TABLE CSM_MAPPING
ADD CONSTRAINT UQ_MP_OBJ_NAME_ATTRI_NAME_APP_ID UNIQUE (OBJECT_NAME,ATTRIBUTE_NAME,APPLICATION_ID)
;

ALTER TABLE CSM_APPLICATION ADD COLUMN CSM_VERSION character varying(20);
