/*L
   Copyright SAIC, SAIC-Frederick

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/common-security-module/LICENSE.txt for details.
L*/


CREATE SEQUENCE CSM_FILTER_CLAUSE_SEQ;

CREATE TABLE CSM_FILTER_CLAUSE ( 
	FILTER_CLAUSE_ID int8 NOT NULL default nextval('CSM_FILTER_CLAUSE_SEQ'),
	CLASS_NAME character varying(100) NOT NULL,
	FILTER_CHAIN character varying(2000) NOT NULL,
	TARGET_CLASS_NAME character varying(100) NOT NULL,
	TARGET_CLASS_ATTRIBUTE_NAME character varying(100) NOT NULL,
	TARGET_CLASS_ATTRIBUTE_TYPE character varying(100) NOT NULL,
	TARGET_CLASS_ALIAS character varying(100),
	TARGET_CLASS_ATTRIBUTE_ALIAS character varying(100),
	GENERATED_SQL character varying(4000) NOT NULL,
	APPLICATION_ID int8 NOT NULL,
	UPDATE_DATE date DEFAULT CURRENT_DATE NOT NULL,
	PRIMARY KEY(FILTER_CLAUSE_ID)	
);

ALTER TABLE CSM_PROTECTION_ELEMENT ADD COLUMN ATTRIBUTE_VALUE character varying(100);
ALTER TABLE CSM_PROTECTION_ELEMENT DROP CONSTRAINT UQ_PE_PE_NAME_ATTRIBUTE_APP_ID;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD CONSTRAINT UQ_PE_PE_NAME_ATTRIBUTE_VALUE_APP_ID UNIQUE (OBJECT_ID, ATTRIBUTE, ATTRIBUTE_VALUE, APPLICATION_ID);
