/*L
   Copyright Ekagra Software Technologies Ltd.
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/common-security-module/LICENSE.txt for details.
L*/

# Replace the <<database_name>> with proper database name that is to be migrated.

USE <<database_name>>;

ALTER TABLE CSM_USER ADD ( 
  PASSWORD_EXPIRED NUMBER(1),
  PASSWORD_EXPIRY_DATE DATE ,
  FIRST_TIME_LOGIN NUMBER(1),
  ACTIVE_FLAG NUMBER(1)
)
/

CREATE TABLE CSM_PASSWORD_HISTORY (
	CSM_PASSWORD_HISTORY_ID NUMBER(38) NOT NULL,
	LOGIN_NAME VARCHAR2(100),
	PASSWORD VARCHAR2(255)
)
/

CREATE SEQUENCE CSM_PASSWORD_HISTORY_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder
/


CREATE OR REPLACE TRIGGER SET_CSM_PASSWORD_HISTORY
BEFORE INSERT
ON CSM_PASSWORD_HISTORY
FOR EACH ROW
BEGIN
  SELECT CSM_PASSWORD_HISTORY_SEQ.NEXTVAL
  INTO :NEW.CSM_PASSWORD_HISTORY_ID
  FROM DUAL;
END;
/

CREATE TABLE CSM_CONFIGURATION_PROPS (
  PROPERTY_KEY VARCHAR(300) NOT NULL,
  PROPERTY_VALUE VARCHAR(3000)
) 
/

ALTER TABLE CSM_CONFIGURATION_PROPS ADD CONSTRAINT PK_CSM_CONFIGURATION_PROPS
PRIMARY KEY (PROPERTY_KEY) 
/

INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('ALLOWED_ATTEMPTS','3')
/
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('ALLOWED_LOGIN_TIME','600000')
/
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_EXPIRY_DAYS','60')
/
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_LOCKOUT_TIME','1800000')
/
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_MATCH_NUM','24')
/
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('AES_ENCRYPTION_KEY','super secret')
/
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_PATTERN_MATCH','^.*(?=.{8,})(?=..*[0-9])(?=.*[a-z])(?=.*[A-Z]).*$')
/
INSERT INTO CSM_CONFIGURATION_PROPS (PROPERTY_KEY, PROPERTY_VALUE) VALUES('PASSWORD_PATTERN_DESCRIPTION','At least one Upper case alphabet, at least one lower case alphabet, at least one number and minimum 8 characters length')
/
COMMIT
/
