# Replace the <<database_name>> with proper database name that is to be created.

USE <<database_name>>;

ALTER TABLE `csm_application` MODIFY COLUMN `DECLARATIVE_FLAG` NUMBER(1) NOT NULL DEFAULT 0;
ALTER TABLE CSM_PROTECTION_ELEMENT DROP COLUMN PROTECTION_ELEMENT_TYPE_ID;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD PROTECTION_ELEMENT_TYPE VARCHAR(100);
ALTER TABLE CSM_PG_PE MODIFY COLUMN UPDATE_DATE DATE;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD UNIQUE UQ_PE_OBJECT_ID_ATTRIBUTE_APP_ID(PROTECTION_ELEMENT_NAME, ATTRIBUTE, APPLICATION_ID);
ALTER TABLE CSM_APPLICATION MODIFY APPLICATION_NAME varchar2(255) NOT NULL;
ALTER TABLE CSM_GROUP MODIFY GROUP_NAME varchar2(255) NOT NULL;
ALTER TABLE CSM_APPLICATION ADD DATABASE_URL VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD DATABASE_USER_NAME VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD DATABASE_PASSWORD VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD DATABASE_DIALECT VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD DATABASE_DRIVER VARCHAR(100);


UPDATE csm_application SET csm_application.DECLARATIVE_FLAG='0';
UPDATE csm_pg_pe SET UPDATE_DATE=NULL;
