# Replace the <<database_name>> with proper database name that is to be created.

USE <<database_name>>;

ALTER TABLE `csm_application` MODIFY COLUMN `DECLARATIVE_FLAG` NUMBER(1) NOT NULL DEFAULT 0;
ALTER TABLE CSM_PROTECTION_ELEMENT DROP COLUMN PROTECTION_ELEMENT_TYPE_ID;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD PROTECTION_ELEMENT_TYPE VARCHAR(100);

UPDATE csm_application SET csm_application.DECLARATIVE_FLAG='0';

