/*L
   Copyright Ekagra Software Technologies Ltd.
   Copyright SAIC, SAIC-Frederick

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/common-security-module/LICENSE.txt for details.
L*/


CREATE TABLE IF NOT EXISTS CSM_MAPPING (
  MAPPING_ID bigint(20) NOT NULL auto_increment,
  APPLICATION_ID bigint(20) NOT NULL,
  OBJECT_NAME varchar(100) NOT NULL,
  ATTRIBUTE_NAME varchar(100) NOT NULL,
  OBJECT_PACKAGE_NAME varchar(100),
  TABLE_NAME varchar(100),
  TABLE_NAME_GROUP varchar(100),
  TABLE_NAME_USER varchar(100),
  VIEW_NAME_GROUP varchar(100),
  VIEW_NAME_USER varchar(100),
  ACTIVE_FLAG tinyint(1) default '0' NOT NULL,
  MAINTAINED_FLAG tinyint(1) default '0' NOT NULL,	
  UPDATE_DATE date DEFAULT '0000-00-00',
  PRIMARY KEY(MAPPING_ID)
) ENGINE=InnoDB
;

ALTER TABLE CSM_PROTECTION_ELEMENT DROP FOREIGN KEY FK_PE_APPLICATION;

ALTER TABLE CSM_MAPPING ADD CONSTRAINT FK_PE_APPLICATION
FOREIGN KEY (APPLICATION_ID) REFERENCES csm_application (APPLICATION_ID) ON DELETE CASCADE
;
ALTER TABLE CSM_MAPPING
ADD CONSTRAINT UQ_MP_OBJ_NAME_ATTRI_NAME_APP_ID UNIQUE (OBJECT_NAME,ATTRIBUTE_NAME,APPLICATION_ID)
;

ALTER TABLE CSM_APPLICATION ADD COLUMN CSM_VERSION VARCHAR(20);
