DROP TABLE LOGTAB;
DROP TABLE SIGNIN_USERS;

CREATE TABLE LOGTAB (
	OID BIGINT (200) NOT NULL AUTO_INCREMENT, 
	APPLICATION VARCHAR(25),
	SERVER VARCHAR(50),
	PRIORITY VARCHAR(15), 
	CATEGORY VARCHAR(255), 
	THREAD VARCHAR(255), 
	MSG TEXT,
	THROWABLE TEXT,
	NDC TEXT, 
	CREATED_ON BIGINT (20) NOT NULL,
	PRIMARY KEY ( OID ) );

create index OID_LOGTAB_INDX on LOGTAB(OID);
create index APPLICATION_LOGTAB_INDX on LOGTAB(APPLICATION);
create index SERVER_LOGTAB_INDX on LOGTAB(SERVER);
create index PRIORITY_LOGTAB_INDX on LOGTAB(PRIORITY);
create index THREAD_LOGTAB_INDX on LOGTAB(THREAD);
create index CREATED_ON_LOGTAB_INDX on LOGTAB(CREATED_ON);

CREATE TABLE SIGNIN_USERS (
       USERNAME VARCHAR(255) NOT NULL,
       PASSWORD VARCHAR(255),
       PRIMARY KEY(USERNAME) );

create index USERNAME_SIGNIN_USERS_INDEX on SIGNIN_USERS(USERNAME);
create index PASSWORD_SIGNIN_USERS_PASSWORD on SIGNIN_USERS(PASSWORD);


INSERT INTO signin_users (username, password) VALUES ('admin','pX4bLclVVdFwnQoyStFF3jIVAYI=');
