/*L
   Copyright Ekagra Software Technologies Ltd.
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/common-security-module/LICENSE.txt for details.
L*/

#Use csm_dev_bkwrdscmptbl_3_2;

ALTER TABLE csm_application MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_group MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_pg_pe MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_privilege MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_protection_element MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_protection_group MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_role MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_role_privilege MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_user MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_user_group_role_pg MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE csm_user_pe MODIFY COLUMN UPDATE_DATE DATE NOT NULL DEFAULT '0000-00-00';
