CREATE SEQUENCE SEQ_ELEMENTID INCREMENT BY 1 START WITH 10000 MINVALUE 0 NOCYCLE NOCACHE ORDER;
CREATE SEQUENCE SEQ_APPID INCREMENT BY 1 START WITH 10000 MINVALUE 0 NOCYCLE NOCACHE ORDER;
CREATE SEQUENCE SEQ_APP_PROTECTION_ELEMID INCREMENT BY 1 START WITH 10000 MINVALUE 0 NOCYCLE NOCACHE ORDER;
CREATE SEQUENCE SEQ_LOGID INCREMENT BY 1 START WITH 10000 MINVALUE 0 NOCYCLE NOCACHE ORDER;
CREATE SEQUENCE SEQ_ROLEID INCREMENT BY 1 START WITH 10000 MINVALUE 0 NOCYCLE NOCACHE ORDER;
CREATE SEQUENCE SEQ_URPAID INCREMENT BY 1 START WITH 10000 MINVALUE 0 NOCYCLE NOCACHE ORDER;
CREATE SEQUENCE SEQ_USERID INCREMENT BY 1 START WITH 10000 MINVALUE 0 NOCYCLE NOCACHE ORDER;
